-- i-PMP: Schema SAP HANA Cloud
-- text-embedding-3-large produce 3072 dimensioni (EMBED_DIMS=3072)

-- Memoria grezza: tutti i chunk indicizzati
CREATE TABLE IF NOT EXISTS IPMP_DOCS (
    ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID  NVARCHAR(50)  NOT NULL,
    SOURCE_NAME NVARCHAR(500),                  -- prefisso 'CONTRATTO::' per il contratto
    CONTENT     NCLOB,
    EMBEDDING   REAL_VECTOR(3072),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Decision Log: decisioni strutturate estratte dai documenti
CREATE TABLE IF NOT EXISTS IPMP_DECISIONS (
    ID             INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID     NVARCHAR(50) NOT NULL,
    DESCRIZIONE    NCLOB,
    AUTORE         NVARCHAR(200),
    DATA_DECISIONE DATE,
    MOTIVAZIONE    NCLOB,
    SOURCE_NAME    NVARCHAR(500),
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Context Layer: riassunti documento-livello per domande trasversali
CREATE TABLE IF NOT EXISTS IPMP_CONTEXT (
    ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID  NVARCHAR(50)  NOT NULL,
    SOURCE_NAME NVARCHAR(500),
    SUMMARY     NCLOB,
    EMBEDDING   REAL_VECTOR(3072),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Alert Scope Guardian
CREATE TABLE IF NOT EXISTS IPMP_ALERTS (
    ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID  NVARCHAR(50) NOT NULL,
    SOURCE_NAME NVARCHAR(500),
    ALERT_TEXT  NCLOB,
    CR_DRAFT    NCLOB,
    IS_HANDLED  TINYINT DEFAULT 0,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indici vettoriali per ricerca semantica
CREATE VECTOR INDEX IPMP_DOCS_VEC_IDX    ON IPMP_DOCS(EMBEDDING)    SIMILARITY FUNCTION COSINE;
CREATE VECTOR INDEX IPMP_CONTEXT_VEC_IDX ON IPMP_CONTEXT(EMBEDDING) SIMILARITY FUNCTION COSINE;
