CREATE TABLE IF NOT EXISTS IPMP_DOCS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECT_ID TEXT NOT NULL,
    SOURCE_NAME TEXT,
    CONTENT TEXT,
    EMBEDDING TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS IPMP_DECISIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECT_ID TEXT NOT NULL,
    DESCRIZIONE TEXT,
    AUTORE TEXT,
    DATA_DECISIONE TEXT,
    MOTIVAZIONE TEXT,
    SOURCE_NAME TEXT,
    EMBEDDING TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS IPMP_CONTEXT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECT_ID TEXT NOT NULL,
    SOURCE_NAME TEXT,
    SUMMARY TEXT,
    EMBEDDING TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS IPMP_ALERTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECT_ID TEXT NOT NULL,
    SOURCE_NAME TEXT,
    ALERT_TEXT TEXT,
    CR_DRAFT TEXT,
    IS_HANDLED INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
